# Generated by Django 4.1.4 on 2023-02-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvmodel',
            name='volume',
            field=models.FloatField(default='null'),
        ),
    ]
